name: "Mattermost Test"

on: push

jobs:
  notify:
    if: always()
    name: Post Workflow Status to Mattermost
    runs-on: ubuntu-latest

    steps:
    - name: Create the Mattermost Message
      run:
        # TODO: props.card needs to have the logs properly escaped
        echo "{\"text\":\"foobar\", \"icon-url\": \"https://annaelizabeth2019.github.io/the-rock-paper-scissors-2/images/therock1.jpg\", \"username\": \"woky\"}" > mattermost.json

    - uses: mattermost/action-mattermost-notify@master
      env:
        MATTERMOST_WEBHOOK_URL: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
        MATTERMOST_ICON: https://annaelizabeth2019.github.io/the-rock-paper-scissors-2/images/therock1.jpg
        MATTERMOST_USERNAME: cicero
