name: "Mattermost Test"

on: push

jobs:
  notify:
    if: always()
    name: Post Workflow Status to Mattermost
    runs-on: ubuntu-latest

    steps:
    - name: Create the Mattermost Message
      run: |

        msg="Message"
        logfile=logfile.txt

        find /var >logfile.txt

        jq -n \
            --arg message "$msg" \
            --rawfile logfile "$logfile" \
            -f /dev/stdin <<'EOF' >mattermost.json
        {
            text: $message,
            props: {
                card: $logfile,
            }
        }
        EOF

    - uses: mattermost/action-mattermost-notify@master
      env:
        MATTERMOST_WEBHOOK_URL: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
        MATTERMOST_ICON: https://annaelizabeth2019.github.io/the-rock-paper-scissors-2/images/therock1.jpg
        MATTERMOST_USERNAME: cicero
